package com.dataobject;

public class ItemStockDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_itemstock.id
     *
     * @mbg.generated Sat Jul 20 17:52:48 IST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_itemstock.stock
     *
     * @mbg.generated Sat Jul 20 17:52:48 IST 2024
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_itemstock.item_id
     *
     * @mbg.generated Sat Jul 20 17:52:48 IST 2024
     */
    private Integer itemId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_itemstock.id
     *
     * @return the value of t_itemstock.id
     *
     * @mbg.generated Sat Jul 20 17:52:48 IST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_itemstock.id
     *
     * @param id the value for t_itemstock.id
     *
     * @mbg.generated Sat Jul 20 17:52:48 IST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_itemstock.stock
     *
     * @return the value of t_itemstock.stock
     *
     * @mbg.generated Sat Jul 20 17:52:48 IST 2024
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_itemstock.stock
     *
     * @param stock the value for t_itemstock.stock
     *
     * @mbg.generated Sat Jul 20 17:52:48 IST 2024
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_itemstock.item_id
     *
     * @return the value of t_itemstock.item_id
     *
     * @mbg.generated Sat Jul 20 17:52:48 IST 2024
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_itemstock.item_id
     *
     * @param itemId the value for t_itemstock.item_id
     *
     * @mbg.generated Sat Jul 20 17:52:48 IST 2024
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }
}