package com.dataobject;

import java.math.BigDecimal;

public class OrderDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderinfo.id
     *
     * @mbg.generated Sun Jul 21 09:49:49 IST 2024
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderinfo.user_id
     *
     * @mbg.generated Sun Jul 21 09:49:49 IST 2024
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderinfo.item_id
     *
     * @mbg.generated Sun Jul 21 09:49:49 IST 2024
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderinfo.item_price
     *
     * @mbg.generated Sun Jul 21 09:49:49 IST 2024
     */
    private BigDecimal itemPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderinfo.amount
     *
     * @mbg.generated Sun Jul 21 09:49:49 IST 2024
     */
    private Integer amount;


    private BigDecimal orderPrice;

    private Integer promoId;

    public Integer getPromoId() {
        return promoId;
    }

    public void setPromoId(Integer promoId) {
        this.promoId = promoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderinfo.id
     *
     * @return the value of t_orderinfo.id
     *
     * @mbg.generated Sun Jul 21 09:49:49 IST 2024
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderinfo.id
     *
     * @param id the value for t_orderinfo.id
     *
     * @mbg.generated Sun Jul 21 09:49:49 IST 2024
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderinfo.user_id
     *
     * @return the value of t_orderinfo.user_id
     *
     * @mbg.generated Sun Jul 21 09:49:49 IST 2024
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderinfo.user_id
     *
     * @param userId the value for t_orderinfo.user_id
     *
     * @mbg.generated Sun Jul 21 09:49:49 IST 2024
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderinfo.item_id
     *
     * @return the value of t_orderinfo.item_id
     *
     * @mbg.generated Sun Jul 21 09:49:49 IST 2024
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderinfo.item_id
     *
     * @param itemId the value for t_orderinfo.item_id
     *
     * @mbg.generated Sun Jul 21 09:49:49 IST 2024
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderinfo.item_price
     *
     * @return the value of t_orderinfo.item_price
     *
     * @mbg.generated Sun Jul 21 09:49:49 IST 2024
     */
    public BigDecimal getItemPrice() {
        return itemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderinfo.item_price
     *
     * @param itemPrice the value for t_orderinfo.item_price
     *
     * @mbg.generated Sun Jul 21 09:49:49 IST 2024
     */
    public void setItemPrice(BigDecimal itemPrice) {
        this.itemPrice = itemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderinfo.amount
     *
     * @return the value of t_orderinfo.amount
     *
     * @mbg.generated Sun Jul 21 09:49:49 IST 2024
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderinfo.amount
     *
     * @param amount the value for t_orderinfo.amount
     *
     * @mbg.generated Sun Jul 21 09:49:49 IST 2024
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }



    public BigDecimal getOrderPrice() {
        return orderPrice;
    }

    public void setOrderPrice(BigDecimal orderPrice) {
        this.orderPrice = orderPrice;
    }
}