package com.dataobject;

public class SequenceDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sequenceinfo.name
     *
     * @mbg.generated Sun Jul 21 10:39:09 IST 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sequenceinfo.current_value
     *
     * @mbg.generated Sun Jul 21 10:39:09 IST 2024
     */
    private Integer currentValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sequenceinfo.step
     *
     * @mbg.generated Sun Jul 21 10:39:09 IST 2024
     */
    private Integer step;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sequenceinfo.name
     *
     * @return the value of t_sequenceinfo.name
     *
     * @mbg.generated Sun Jul 21 10:39:09 IST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sequenceinfo.name
     *
     * @param name the value for t_sequenceinfo.name
     *
     * @mbg.generated Sun Jul 21 10:39:09 IST 2024
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sequenceinfo.current_value
     *
     * @return the value of t_sequenceinfo.current_value
     *
     * @mbg.generated Sun Jul 21 10:39:09 IST 2024
     */
    public Integer getCurrentValue() {
        return currentValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sequenceinfo.current_value
     *
     * @param currentValue the value for t_sequenceinfo.current_value
     *
     * @mbg.generated Sun Jul 21 10:39:09 IST 2024
     */
    public void setCurrentValue(Integer currentValue) {
        this.currentValue = currentValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sequenceinfo.step
     *
     * @return the value of t_sequenceinfo.step
     *
     * @mbg.generated Sun Jul 21 10:39:09 IST 2024
     */
    public Integer getStep() {
        return step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sequenceinfo.step
     *
     * @param step the value for t_sequenceinfo.step
     *
     * @mbg.generated Sun Jul 21 10:39:09 IST 2024
     */
    public void setStep(Integer step) {
        this.step = step;
    }
}