package com.dataobject;

public class StockLogDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stocklog.stock_log_id
     *
     * @mbg.generated Wed Jul 24 15:44:24 IST 2024
     */
    private String stockLogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stocklog.item_id
     *
     * @mbg.generated Wed Jul 24 15:44:24 IST 2024
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stocklog.amount
     *
     * @mbg.generated Wed Jul 24 15:44:24 IST 2024
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stocklog.status
     *
     * @mbg.generated Wed Jul 24 15:44:24 IST 2024
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stocklog.stock_log_id
     *
     * @return the value of t_stocklog.stock_log_id
     *
     * @mbg.generated Wed Jul 24 15:44:24 IST 2024
     */
    public String getStockLogId() {
        return stockLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stocklog.stock_log_id
     *
     * @param stockLogId the value for t_stocklog.stock_log_id
     *
     * @mbg.generated Wed Jul 24 15:44:24 IST 2024
     */
    public void setStockLogId(String stockLogId) {
        this.stockLogId = stockLogId == null ? null : stockLogId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stocklog.item_id
     *
     * @return the value of t_stocklog.item_id
     *
     * @mbg.generated Wed Jul 24 15:44:24 IST 2024
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stocklog.item_id
     *
     * @param itemId the value for t_stocklog.item_id
     *
     * @mbg.generated Wed Jul 24 15:44:24 IST 2024
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stocklog.amount
     *
     * @return the value of t_stocklog.amount
     *
     * @mbg.generated Wed Jul 24 15:44:24 IST 2024
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stocklog.amount
     *
     * @param amount the value for t_stocklog.amount
     *
     * @mbg.generated Wed Jul 24 15:44:24 IST 2024
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stocklog.status
     *
     * @return the value of t_stocklog.status
     *
     * @mbg.generated Wed Jul 24 15:44:24 IST 2024
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stocklog.status
     *
     * @param status the value for t_stocklog.status
     *
     * @mbg.generated Wed Jul 24 15:44:24 IST 2024
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}