package com.dataobject;

public class UserPasswordDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_userpassword.id
     *
     * @mbg.generated Fri Jul 19 22:29:12 IST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_userpassword.encrypt_password
     *
     * @mbg.generated Fri Jul 19 22:29:12 IST 2024
     */
    private String encryptPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_userpassword.user_id
     *
     * @mbg.generated Fri Jul 19 22:29:12 IST 2024
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_userpassword.id
     *
     * @return the value of t_userpassword.id
     *
     * @mbg.generated Fri Jul 19 22:29:12 IST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_userpassword.id
     *
     * @param id the value for t_userpassword.id
     *
     * @mbg.generated Fri Jul 19 22:29:12 IST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_userpassword.encrypt_password
     *
     * @return the value of t_userpassword.encrypt_password
     *
     * @mbg.generated Fri Jul 19 22:29:12 IST 2024
     */
    public String getEncryptPassword() {
        return encryptPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_userpassword.encrypt_password
     *
     * @param encryptPassword the value for t_userpassword.encrypt_password
     *
     * @mbg.generated Fri Jul 19 22:29:12 IST 2024
     */
    public void setEncryptPassword(String encryptPassword) {
        this.encryptPassword = encryptPassword == null ? null : encryptPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_userpassword.user_id
     *
     * @return the value of t_userpassword.user_id
     *
     * @mbg.generated Fri Jul 19 22:29:12 IST 2024
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_userpassword.user_id
     *
     * @param userId the value for t_userpassword.user_id
     *
     * @mbg.generated Fri Jul 19 22:29:12 IST 2024
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}