package com.dataobject;

public class UserDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_userinfo.id
     *
     * @mbg.generated Fri Jul 19 22:29:12 IST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_userinfo.name
     *
     * @mbg.generated Fri Jul 19 22:29:12 IST 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_userinfo.gender
     *
     * @mbg.generated Fri Jul 19 22:29:12 IST 2024
     */
    private Integer gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_userinfo.age
     *
     * @mbg.generated Fri Jul 19 22:29:12 IST 2024
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_userinfo.telephone
     *
     * @mbg.generated Fri Jul 19 22:29:12 IST 2024
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_userinfo.register_mode
     *
     * @mbg.generated Fri Jul 19 22:29:12 IST 2024
     */
    private String registerMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_userinfo.third_party_id
     *
     * @mbg.generated Fri Jul 19 22:29:12 IST 2024
     */
    private String thirdPartyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_userinfo.id
     *
     * @return the value of t_userinfo.id
     *
     * @mbg.generated Fri Jul 19 22:29:12 IST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_userinfo.id
     *
     * @param id the value for t_userinfo.id
     *
     * @mbg.generated Fri Jul 19 22:29:12 IST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_userinfo.name
     *
     * @return the value of t_userinfo.name
     *
     * @mbg.generated Fri Jul 19 22:29:12 IST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_userinfo.name
     *
     * @param name the value for t_userinfo.name
     *
     * @mbg.generated Fri Jul 19 22:29:12 IST 2024
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_userinfo.gender
     *
     * @return the value of t_userinfo.gender
     *
     * @mbg.generated Fri Jul 19 22:29:12 IST 2024
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_userinfo.gender
     *
     * @param gender the value for t_userinfo.gender
     *
     * @mbg.generated Fri Jul 19 22:29:12 IST 2024
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_userinfo.age
     *
     * @return the value of t_userinfo.age
     *
     * @mbg.generated Fri Jul 19 22:29:12 IST 2024
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_userinfo.age
     *
     * @param age the value for t_userinfo.age
     *
     * @mbg.generated Fri Jul 19 22:29:12 IST 2024
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_userinfo.telephone
     *
     * @return the value of t_userinfo.telephone
     *
     * @mbg.generated Fri Jul 19 22:29:12 IST 2024
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_userinfo.telephone
     *
     * @param telephone the value for t_userinfo.telephone
     *
     * @mbg.generated Fri Jul 19 22:29:12 IST 2024
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_userinfo.register_mode
     *
     * @return the value of t_userinfo.register_mode
     *
     * @mbg.generated Fri Jul 19 22:29:12 IST 2024
     */
    public String getRegisterMode() {
        return registerMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_userinfo.register_mode
     *
     * @param registerMode the value for t_userinfo.register_mode
     *
     * @mbg.generated Fri Jul 19 22:29:12 IST 2024
     */
    public void setRegisterMode(String registerMode) {
        this.registerMode = registerMode == null ? null : registerMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_userinfo.third_party_id
     *
     * @return the value of t_userinfo.third_party_id
     *
     * @mbg.generated Fri Jul 19 22:29:12 IST 2024
     */
    public String getThirdPartyId() {
        return thirdPartyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_userinfo.third_party_id
     *
     * @param thirdPartyId the value for t_userinfo.third_party_id
     *
     * @mbg.generated Fri Jul 19 22:29:12 IST 2024
     */
    public void setThirdPartyId(String thirdPartyId) {
        this.thirdPartyId = thirdPartyId == null ? null : thirdPartyId.trim();
    }
}