package com.dao;

import com.dataobject.ItemStockDO;

public interface ItemStockDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_itemstock
     *
     * @mbg.generated Sat Jul 20 17:52:48 IST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_itemstock
     *
     * @mbg.generated Sat Jul 20 17:52:48 IST 2024
     */
    int insert(ItemStockDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_itemstock
     *
     * @mbg.generated Sat Jul 20 17:52:48 IST 2024
     */
    int insertSelective(ItemStockDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_itemstock
     *
     * @mbg.generated Sat Jul 20 17:52:48 IST 2024
     */
    ItemStockDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_itemstock
     *
     * @mbg.generated Sat Jul 20 17:52:48 IST 2024
     */
    ItemStockDO selectByItemId(Integer itemId);

    int updateByPrimaryKeySelective(ItemStockDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_itemstock
     *
     * @mbg.generated Sat Jul 20 17:52:48 IST 2024
     */
    int updateByPrimaryKey(ItemStockDO row);
}