package com.dao;

import com.dataobject.ItemDO;

public interface ItemDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbg.generated Sat Jul 20 17:52:48 IST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbg.generated Sat Jul 20 17:52:48 IST 2024
     */
    int insert(ItemDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbg.generated Sat Jul 20 17:52:48 IST 2024
     */
    int insertSelective(ItemDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbg.generated Sat Jul 20 17:52:48 IST 2024
     */
    ItemDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbg.generated Sat Jul 20 17:52:48 IST 2024
     */
    int updateByPrimaryKeySelective(ItemDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbg.generated Sat Jul 20 17:52:48 IST 2024
     */
    int updateByPrimaryKey(ItemDO row);
}