package com.dao;

import com.dataobject.PromoDO;

public interface PromoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_promo
     *
     * @mbg.generated Sun Jul 21 12:51:34 IST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_promo
     *
     * @mbg.generated Sun Jul 21 12:51:34 IST 2024
     */
    int insert(PromoDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_promo
     *
     * @mbg.generated Sun Jul 21 12:51:34 IST 2024
     */
    int insertSelective(PromoDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_promo
     *
     * @mbg.generated Sun Jul 21 12:51:34 IST 2024
     */
    PromoDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_promo
     *
     * @mbg.generated Sun Jul 21 12:51:34 IST 2024
     */
    int updateByPrimaryKeySelective(PromoDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_promo
     *
     * @mbg.generated Sun Jul 21 12:51:34 IST 2024
     */
    int updateByPrimaryKey(PromoDO row);

    PromoDO selectByItemId(Integer itemId);
}