package com.dao;

import com.dataobject.StockLogDO;

public interface StockLogDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stocklog
     *
     * @mbg.generated Wed Jul 24 15:44:24 IST 2024
     */
    int deleteByPrimaryKey(String stockLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stocklog
     *
     * @mbg.generated Wed Jul 24 15:44:24 IST 2024
     */
    int insert(StockLogDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stocklog
     *
     * @mbg.generated Wed Jul 24 15:44:24 IST 2024
     */
    int insertSelective(StockLogDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stocklog
     *
     * @mbg.generated Wed Jul 24 15:44:24 IST 2024
     */
    StockLogDO selectByPrimaryKey(String stockLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stocklog
     *
     * @mbg.generated Wed Jul 24 15:44:24 IST 2024
     */
    int updateByPrimaryKeySelective(StockLogDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stocklog
     *
     * @mbg.generated Wed Jul 24 15:44:24 IST 2024
     */
    int updateByPrimaryKey(StockLogDO row);
}